development:
  graphite:
    url: <%= ENV['GRAPHITE_URL'] %>

  ganglia:
    url: <%= ENV['GANGLIA_WEB_URL'] %>
    host: <%= ENV['GANGLIA_HOST'] %>

  sensu:
    url: <%= ENV['SENSU_EVENTS_URL'] %>

  uptime:
    url: <%= ENV['UPTIME_URL']  %>

  jira:
    url: <%= ENV['JIRA_URL'] %> # e.g. "http://your-jira-installation/rest/api/latest/search"
    user: <%= ENV['JIRA_USER'] %>
    password: <%= ENV['JIRA_PASSWORD'] %>

  pingdom:
    user: <%= ENV['PINGDOM_USER'] %>
    password: <%= ENV['PINGDOM_PASSWORD'] %>
    api_key:

  new_relic:
    api_key:

test:
production:
  graphite:
    url: <%= ENV['GRAPHITE_URL'] %>

  ganglia:
    url: <%= ENV['GANGLIA_WEB_URL'] %>
    host: <%= ENV['GANGLIA_HOST'] %>

  sensu:
    url: <%= ENV['SENSU_EVENTS_URL'] %>

  uptime:
    url: <%= ENV['UPTIME_URL']  %>

  jira:
    url: <%= ENV['JIRA_URL'] %> # e.g. "http://your-jira-installation/rest/api/latest/search"
    user: <%= ENV['JIRA_USER'] %>
    password: <%= ENV['JIRA_PASSWORD'] %>

  pingdom:
    user: <%= ENV['PINGDOM_USER'] %>
    password: <%= ENV['PINGDOM_PASSWORD'] %>
    api_key:

  new_relic:
    api_key: